/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    colors: {
      transparent: "transparent",
      current: "currentColor",
      white: "#fafafa",
      realwhite: "#ffffff",
      purple: "#7148FC",
      midpurple: "#6E56CF",
      primepurple: "#4c33b3",
      "light-purple": "#D8CDFF",
      guild: "#101013",
      guildbc: "#303E59",
      darkbg: "#19191d",
      lightbg: "#f8f9fa",
      "border-dark-hue": "#24242b",
      lightborder: "#9ea6b5",
      "search-button-bg": "#191c21",
      "search-button-tc": "#8690a3",
      buttonlight: "#eceef0",
      danger: "#EE1739",
      "sidebar-link-bg": "#09090b",
      "sidebar-hoverlink-bg": "#0d0d0f",
      dark_nitro: "#121213",
      card_background: "#1c1f26",
      card_border_color: "#2c313a",
      card_border_color_hover: "#4a5262",
      dark_nitro_hover: "#212124",
      linkpreviewbg: "#141416",
      linkpreviewbc: "#1d1d20",
      purple2: "#AE96FD",
      royalblue: "#3B82F6",
      metal: "#CBD5E1",
      midnightblue: "#0F172A",
      skynight: "#304065",
      "royalblue-dark-momentum": "#426AC6",
      purpleisfriendly: "#8860EF",
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        none: "0",
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        DEFAULT: "4px",
        md: "0.375rem",
        lg: "0.5rem",
        full: "9999px",
        large: "12px",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
