import { SignIn } from "@clerk/nextjs";
import ath from "@/styles/auth.module.css";
import Head from "next/head";

export default function Page() {
  return (
    <>
      <Head>
        <title>Resubase - Sign In Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={ath.wrapper}>
        <SignIn />
      </div>
    </>
  );
}
